containers:
- name: postgres
  image: postgres:17
  ports:
  - containerPort: 5432
  env:
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: postgres-sec
          key: username

    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-sec
          key: password

    - name: POSTGRES_DB
      value: mydatabase

    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata

  volumeMounts:
    - name: postgres-volume
      mountPath: /var/lib/postgresql/data